In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/countrydata.csv')

In [ ]:
df.head()

Country   Age   Salary Purchased
0     France  44.0  72000.0       Yes
1      Spain  52.0  55000.0        No
2    Germany  32.0  25000.0        No
3  Amsterdam   NaN  65000.0       Yes
4      Spain  23.0  85000.0       Yes

In [ ]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    18 non-null     object 
 1   Age        13 non-null     float64
 2   Salary     12 non-null     float64
 3   Purchased  18 non-null     object 
dtypes: float64(2), object(2)
memory usage: 704.0+ bytes


In [ ]:
df.describe()

Age        Salary
count  13.000000     12.000000
mean   33.076923  43833.333333
std    11.228398  23272.431343
min    16.000000  18000.000000
25%    26.000000  24750.000000
50%    32.000000  34000.000000
75%    34.000000  65250.000000
max    55.000000  85000.000000

In [ ]:
df.shape

(18, 4)

In [ ]:
df.isnull().sum()

Country      0
Age          5
Salary       6
Purchased    0
dtype: int64

Dependent Variables - Purchased
Independednt Variables - Country, Age, Salary

In [ ]:
x=df[['Country','Age','Salary']].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 52.0, 55000.0],
       ['Germany', 32.0, 25000.0],
       ['Amsterdam', nan, 65000.0],
       ['Spain', 23.0, 85000.0],
       ['Germany', 34.0, 36000.0],
       ['Amsterdam', nan, 25000.0],
       ['France', 55.0, nan],
       ['Germany', 16.0, 23000.0],
       ['France', nan, nan],
       ['Amsterdam', 24.0, 66000.0],
       ['France', 26.0, nan],
       ['France', 33.0, nan],
       ['Amsterdam', nan, 18000.0],
       ['Germany', 29.0, 32000.0],
       ['Spain', nan, 24000.0],
       ['Spain', 30.0, nan],
       ['Spain', 32.0, nan]], dtype=object)

In [ ]:
y = df['Purchased'].values
y

array(['Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')

In [ ]:
imputer = imputer.fit(x[:,1:3])


In [ ]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 52.0, 55000.0],
       ['Germany', 32.0, 25000.0],
       ['Amsterdam', 33.07692307692308, 65000.0],
       ['Spain', 23.0, 85000.0],
       ['Germany', 34.0, 36000.0],
       ['Amsterdam', 33.07692307692308, 25000.0],
       ['France', 55.0, 43833.333333333336],
       ['Germany', 16.0, 23000.0],
       ['France', 33.07692307692308, 43833.333333333336],
       ['Amsterdam', 24.0, 66000.0],
       ['France', 26.0, 43833.333333333336],
       ['France', 33.0, 43833.333333333336],
       ['Amsterdam', 33.07692307692308, 18000.0],
       ['Germany', 29.0, 32000.0],
       ['Spain', 33.07692307692308, 24000.0],
       ['Spain', 30.0, 43833.333333333336],
       ['Spain', 32.0, 43833.333333333336]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encode_x=LabelEncoder()

In [ ]:
x[:,0] = label_encode_x.fit_transform(x[:,0])

In [ ]:
x

array([[1, 44.0, 72000.0],
       [3, 52.0, 55000.0],
       [2, 32.0, 25000.0],
       [0, 33.07692307692308, 65000.0],
       [3, 23.0, 85000.0],
       [2, 34.0, 36000.0],
       [0, 33.07692307692308, 25000.0],
       [1, 55.0, 43833.333333333336],
       [2, 16.0, 23000.0],
       [1, 33.07692307692308, 43833.333333333336],
       [0, 24.0, 66000.0],
       [1, 26.0, 43833.333333333336],
       [1, 33.0, 43833.333333333336],
       [0, 33.07692307692308, 18000.0],
       [2, 29.0, 32000.0],
       [3, 33.07692307692308, 24000.0],
       [3, 30.0, 43833.333333333336],
       [3, 32.0, 43833.333333333336]], dtype=object)

France = 1
spain= 3
germany = 2
Amsterdam = 0 
We will use dummy encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
onehotencoder = OneHotEncoder()

In [ ]:
onehotencoder.fit_transform(df.Country.values.reshape(-1,1)).toarray()

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [ ]:
label_encode_y = LabelEncoder()

In [ ]:
y = label_encode_y.fit_transform(y)

In [ ]:
y

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train

array([[2, 29.0, 32000.0],
       [3, 23.0, 85000.0],
       [2, 32.0, 25000.0],
       [3, 30.0, 43833.333333333336],
       [3, 32.0, 43833.333333333336],
       [1, 33.07692307692308, 43833.333333333336],
       [1, 55.0, 43833.333333333336],
       [0, 33.07692307692308, 18000.0],
       [1, 26.0, 43833.333333333336],
       [0, 33.07692307692308, 65000.0],
       [1, 44.0, 72000.0],
       [2, 34.0, 36000.0],
       [3, 33.07692307692308, 24000.0],
       [1, 33.0, 43833.333333333336]], dtype=object)

In [ ]:
x_test

array([[3, 52.0, 55000.0],
       [0, 33.07692307692308, 25000.0],
       [2, 16.0, 23000.0],
       [0, 24.0, 66000.0]], dtype=object)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0])

In [ ]:
y_test

array([0, 1, 1, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc_x = StandardScaler()

In [ ]:
x_train = sc_x.fit_transform(x_train)

In [ ]:
x_test = sc_x.transform(x_test)

In [ ]:
x_train

array([[ 0.34259435, -0.6165413 , -0.68148703],
       [ 1.30185855, -1.42187995,  2.25841632],
       [ 0.34259435, -0.21387198, -1.06977615],
       [ 1.30185855, -0.4823182 , -0.02509351],
       [ 1.30185855, -0.21387198, -0.02509351],
       [-0.61666984, -0.06932402, -0.02509351],
       [-0.61666984,  2.87325948, -0.02509351],
       [-1.57593403, -0.06932402, -1.45806527],
       [-0.61666984, -1.01921063, -0.02509351],
       [-1.57593403, -0.06932402,  1.14901883],
       [-0.61666984,  1.3968053 ,  1.53730795],
       [ 0.34259435,  0.05457423, -0.45960753],
       [ 1.30185855, -0.06932402, -1.12524603],
       [-0.61666984, -0.07964888, -0.02509351]])

In [ ]:
x_test

array([[ 1.30185855,  2.47059016,  0.59432008],
       [-1.57593403, -0.06932402, -1.06977615],
       [ 0.34259435, -2.3614417 , -1.1807159 ],
       [-1.57593403, -1.28765684,  1.2044887 ]])